# Generated by Django 4.2.1 on 2023-06-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataPage', '0002_alter_userinfo_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
