# Generated by Django 4.2.1 on 2023-06-08 03:25

import dataPage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataPage', '0004_alter_department_id_alter_userinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigIntegerField(default=dataPage.models.unique_department_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.BigIntegerField(default=dataPage.models.unique_user_id, primary_key=True, serialize=False),
        ),
    ]
