# Generated by Django 4.2.1 on 2023-06-08 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataPage', '0005_alter_department_id_alter_userinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataPage.department', verbose_name='部门'),
        ),
    ]
