# Generated by Django 4.2.2 on 2023-06-16 02:56

import dataPage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataPage', '0006_alter_userinfo_depart'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossJobs',
            fields=[
                ('id', models.BigIntegerField(default=dataPage.models.unique_job_id, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=16, verbose_name='职位名称')),
                ('location', models.CharField(max_length=16, verbose_name='岗位地点')),
                ('salary', models.CharField(max_length=16, verbose_name='薪资待遇')),
                ('experience', models.CharField(max_length=16, verbose_name='工作经验要求')),
                ('education', models.CharField(max_length=16, verbose_name='教育背景要求')),
                ('hr', models.CharField(max_length=16, verbose_name='招聘人')),
                ('status', models.CharField(blank=True, max_length=16, null=True, verbose_name='招聘人状态')),
                ('job_url', models.TextField(blank=True, null=True, verbose_name='职位链接')),
                ('organization_name', models.CharField(blank=True, max_length=16, null=True, verbose_name='公司名称')),
                ('organization_size', models.CharField(blank=True, max_length=16, null=True, verbose_name='公司规模')),
                ('company_url', models.TextField(blank=True, null=True, verbose_name='公司链接')),
            ],
        ),
    ]
