# Generated by Django 4.2.2 on 2023-06-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataPage', '0007_bossjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossjobs',
            name='create_time',
            field=models.DateField(default='20230616', verbose_name='创建时间'),
        ),
    ]
