# Generated by Django 4.2.2 on 2023-06-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataPage', '0008_bossjobs_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bossjobs',
            name='create_time',
            field=models.DateField(default='20230620', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='bossjobs',
            name='education',
            field=models.CharField(max_length=50, verbose_name='教育背景要求'),
        ),
        migrations.AlterField(
            model_name='bossjobs',
            name='experience',
            field=models.CharField(max_length=50, verbose_name='工作经验要求'),
        ),
        migrations.AlterField(
            model_name='bossjobs',
            name='hr',
            field=models.CharField(max_length=50, verbose_name='招聘人'),
        ),
        migrations.AlterField(
            model_name='bossjobs',
            name='job_title',
            field=models.CharField(max_length=50, verbose_name='职位名称'),
        ),
        migrations.AlterField(
            model_name='bossjobs',
            name='location',
            field=models.CharField(max_length=50, verbose_name='岗位地点'),
        ),
        migrations.AlterField(
            model_name='bossjobs',
            name='organization_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='bossjobs',
            name='organization_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='公司规模'),
        ),
        migrations.AlterField(
            model_name='bossjobs',
            name='salary',
            field=models.CharField(max_length=50, verbose_name='薪资待遇'),
        ),
        migrations.AlterField(
            model_name='bossjobs',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='招聘人状态'),
        ),
    ]
